### ISSUE TITLE
ODRC: implement document download/file serve

### ISSUE THREAD

**Issue by sergei-maertens** [GeneriekPublicatiePlatformWoo/registratie-component#133]
The files uploaded to the Documenten API must also be downloadable. The citizen portal/publication component will be frontends for this. These will make API-key authenticated calls to the registration component, which makes authenticated calls to the underlying Documenten API.

Ideally, the binary data is streamed from the documenten API to avoid excessive memory usage/overhead.

The citizen portal will then be able to offer a public download URL, to be included in the generated sitemap.

**Tasks**

- [x] Add API endpoint to download document contents
- [x] Download/stream the file contents from the upstream API.

**Comment by sergei-maertens** [comment]
Download endpoint staat nu live op de testomgeving & zit in de latest docker image

**Comment by MarcoKlerks** [comment]
@felixcicatt Wat mij betreft kan deze op Done. Wat vind jij?

**Comment by felixcicatt** [comment]
@MarcoKlerks wat mij betreft ook, want volgens mij hebben we nu wat we nodig hebben voor het downloaden van bestanden. Toch, @nijmra ?
