### ISSUE TITLE
ODRC: Add eigenaar to document

### ISSUE THREAD

**Issue by nijmra** [GeneriekPublicatiePlatformWoo/registratie-component#162]
Additional information on `document` about ownership, same as on `publicatie`.

```
"eigenaar": {
  "weergaveNaam": "string",
  "identifier": "string"
}
```

When `eigenaar` is present on `document` ownership checks from ODPC will be more straightforward for `/api/v1/documenten...` endpoints.

**Tasks**

- [x] Add extra field to serializer
- [x] Add extra list endpoint filter parameter

**Comment by sergei-maertens** [comment]
@nijmra deze staat nu op de testomgeving!
