### ISSUE TITLE
Onderzoeken downloaden grote bestanden uit ODRC

### ISSUE THREAD

**Issue by felixcicatt** [GeneriekPublicatiePlatformWoo/registratie-component#164]
We hebben een groot bestand (iets meer dan 1GB) geupload en dat is correct doorgekomen in Open Zaak. Vanuit Open Zaak kunnen we dit bestand ook downloaden. Met het onderstaande testscript (uit te voeren in de console van Chrome Devtools, als je op een pagina binnen [de testomgeving](https://woo-publicaties.test.opengem.nl) bent), stokt het downloaden echter in het zicht van de haven. Dit kan met timeouts te maken hebben en is daardoor mogelijk lastig te reproduceren.

```js
const start = new Date();
let totalBytes = 0;
fetch(
  "/api/v1/documenten/dfc02520-ccfa-40dd-a103-30caf35764a8/download",
  {
    headers: {
      Authorization: "Token xyz",
      ["Audit-User-ID"]: "Test",
      ["Audit-User-Representation"]: "Test",
      ["Audit-Remarks"]: "Test",
    },
  }
)
  .then(async (r) => {
    const lengthHeader = r.headers.get("Content-Length");
    if (!r.body || !lengthHeader) return;
    const length = +lengthHeader;
    let previousPercent = 0;
    for await (const element of r.body) {
      totalBytes += element.byteLength;
      const percent = Math.round((totalBytes / length) * 100);
      if (percent > previousPercent) {
        previousPercent = percent;
        console.log(percent + "%");
      }
    }
  })
  .then(() => console.log("success!"))
  .catch(() => console.error("error!"))
  .finally(() =>
    console.log(
      `done after ${(new Date() - start) / 1000} seconds, ${totalBytes} bytes`
    )
  );

```

**Comment by sergei-maertens** [comment]
Let's see what the effect of 5999e9e28d9771f6b4e305a19ec29f639bc50789 is on this :)

**Comment by felixcicatt** [comment]
@sergei-maertens ik krijg het bestand nog niet helemaal binnen, het downloaden stopt steeds rond de 100 seconden

**Comment by sergei-maertens** [comment]
I can reproduce this when setting my network throttle speed to 3G in the dev tools.

**Comment by MarcoKlerks** [comment]
Documenteer engine-X requirements

**Comment by sergei-maertens** [comment]
Documentation added to the installation requirements. The default nginx settings work correctly, so someone would already have to go out of their way to break this, and in these cases we now have docs to refer too.
