### ISSUE TITLE
ODRC: filter op registratiedatumTot is exclusief, dit zorgt voor verwarring in ODPC

### ISSUE THREAD

**Issue by felixcicatt** [GeneriekPublicatiePlatformWoo/registratie-component#180]
In ODPC kan je publicaties filteren op registratiedatumTot. Je kan hier geen datum na vandaag kiezen. Dit is qua interactie logisch. Maar omdat deze datum exclusief (tot) is en niet inclusief (tot en met), betekent dit in de praktijk dat je niet kan filteren op vandaag.

**Comment by sergei-maertens** [comment]
@bart-maykin je kan alle query params die nu `fooTot` heten hernoemen naar `fooTotEnMet` en de lookups aanpassen van `__lt` naar `__lte` :grimacing:

**Comment by MarcoKlerks** [comment]
Duplicate met #181
