### ISSUE TITLE
ODRC: eerste, rudimentaire versie van de beheer-interface

### ISSUE THREAD

**Issue by RutgerICATT** [GeneriekPublicatiePlatformWoo/registratie-component#3]
**Description (why)**
uit PSA: Ook kan al de eerste, rudimentaire versie van de beheer-interface (“Model- en publicatiebeheer”) 
gerealiseerd worden. Deelnemende gemeenten zullen het ongetwijfeld waarderen als het Scrum
team al iets aan hen kan tonen waar zij later mee zullen gaan werken. In deze versie van de beheer
interface zal een beheerder moeten kunnen inloggen. Mogelijk al via SSO? Als eerste functionaliteit 
in de beheer-interface, zodat er niet een leeg scherm te zien is, zou bijvoorbeeld al inzicht gegevens 
kunnen worden in de logging. 

**Acceptance criteria (what)**

**Specific details (how)**

**Test plan**

**Tasks**

- [x] #15
- [x] #5

**Comment by sergei-maertens** [comment]
Considerations for estimate:

**Users and groups**

* SSO: set up mozilla-django-oidc-db & configure it with an IDP somewhere (Keycloak so we can add icatt & Maykin & Dimpact OIDC to it all?) -> perhaps ask @sjoerdie to provision a keycloak instance
* Set up a groups/permissions fixture that automatically gets loaded.
    - Group "Beheerders": has add/change/view/delete permissions on Publication, Document. Has view permissions on logs/audit trails.

**Publications admin**

* Show list of publications. Allow filtering on publication date + display whether it's currently published or not. Display the amount of documents related + link to the (filtered) documents list.
* Add admin action to publish/unpublish publications + add audit logs for these actions.
* Set up proper fieldsets in the Publication admin

**Document admin**

* Show list of documents, display their publication status (via the associated Publication)
* Allow searching on document identifier(s)
* Ensure that it's (audit) logged whenever a user views a document.
* Set up proper fieldsets.

**Admin index**

Organize admin index in logical groups + set up an automatically loaded fixture.

* Publications: Publication, Document
* Accounts: OIDC config, User, Group, API keys
* Logging: audit logs, timeline logger, axes logs...

**Comment by MarcoKlerks** [comment]
User story #6  en #7 vallen niet onder deze "epic". Conform het PSA maken ze niet deel uit van de "eerste, rudimentare versie van de beheer-interface" en dus zijn ze niet voorwaardelijk voor de mijlpaal "ODRC: Basis".

Deze twee user stories zijn wel onderdeel van de mijlpaal "ODRC: beheren publicaties".

(Dit gehannes is relevant voor het kunnen afsluiten van mijlpalen en het rapporteren over de project-voortgang.)
