### ISSUE TITLE
ODRC: expose READ operations for Document resource

### ISSUE THREAD

**Issue by sergei-maertens** [GeneriekPublicatiePlatformWoo/registratie-component#38]
Depends on #37, split of from #2

**Acceptance criteria**

Taken from #2

- Via een API kan een document (data-object) geraadpleegd worden.
- Het is zowel mogelijk:
    - om één document te raadplegen (op basis van de identifier),
    - om een lijst (array) van documenten op te vragen ,
    - om een lijst (array van alle documenten behorende bij één publicatie op te vragen,
    - Bij het opvragen van een lijst kan sortering en pagination toegepast worden.
- Optioneel: de raadpleging van een of meerdere documenten wordt gelogd (zie #16 ). Graag laten weten of dit wordt meegenomen!
- De API specificatie is bijgewerkt (ReDoc, Swagger)
- De documentatie is bijgewerkt (Read the Docs)

**Developer tasks**

- [x] Add API endpoint `/api/v1/documenten` with READ operations (list, detail)
- [x] List endpoint accepts filter parameter on `publicatie`
- [x] List endpoint must be paginated
- [x] List endpoint must support ordering on `officieleTitel`, `verkorteTitel`, `creatiedatum`

**Comment by sergei-maertens** [comment]
-> Leaving the READ operation out of scope initially

**Comment by sergei-maertens** [comment]
@MarcoKlerks  please double check this story if it matches your expectations

**Comment by sergei-maertens** [comment]
Testing needed :)

**Comment by MarcoKlerks** [comment]
Ik kan dit technisch niet testen. Op grond van de documentatie (ReDoc) lijkt mij dit op orde.
