### ISSUE TITLE
ODRC: Publicatie uitbreiden met informatiecategorieën

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/registratie-component#48]
In #35 hebben we gerealiseerd dat een publicatie gecreëerd kan worden. In #14 ontsluiten we de informatiecategorieën. In deze story zorgen we ervoor dat een publicatie aan een of meer informatiecategorieën gekoppeld kan worden.

**Acceptatie criteria**
- Het datamodel wordt uitgebreid zodat op een publicatie een of meer [informatiecategorieën](https://standaarden.overheid.nl/diwoo/metadata/doc/0.9.4/diwoo-metadata_xsd_Complex_Type_diwoo_classificatiecollectieType#classificatiecollectieType_informatiecategorieen) vastgelegd kan worden.
- De API wordt uitgebreid, zodat bij het creëren, raadplegen en muteren van een publicatie ook informatiecategorieën meegegeven kunnen worden.
- Een publicatie moet aan minstens één informatiecategorie gekoppeld zijn.
- De API specificatie is bijgewerkt (ReDoc, Swagger)
- De documentatie is bijgewerkt (Read the Docs)
- Een grafisch datamodel van de database is beschikbaar / bijgewerkt (op GitHub of Read the Docs of elders)

**Taken**

- [x] Ensure a list of UUIDs of information categories can be sent during create/update of publications
- [x] Ensure the information categories can be set/selected in the admin (horizontal select or raw ID widget)
- [x] No data migration required for existing data, we'll fix it up via the admin

**Comment by sergei-maertens** [comment]
Testing required

**Comment by sergei-maertens** [comment]
@MarcoKlerks het API aspect kan je niet testen, dat zal @felixcicatt of een collega moeten doen, maar je kan de admin wel testen :)

**Comment by MarcoKlerks** [comment]
Testbevindingen:

1. Ik kan in de admin-interface niet goed zien welke informatiecategorieën gekoppeld zijn aan een publicatie. Ik kan dit als beheerder dus ook niet goed corrigeren. Ik zie wel een veld `Informatiecategorieën` met enkele cijfers (array), maar ik kan niet achterhalen welk cijfer welke informatiecategorie is.
Voorkeur: ik zie namen i.p.v. cijfers.
Alternatief: ik zie het ID / cijfer in de lijst informatiecategorieën.

**Comment by sergei-maertens** [comment]
@MarcoKlerks - this can be re-tested! Note that we're aware that long labels get cut-off. There exist workarounds for this, but in my opinion those aren't worth the effort *at the moment*.
