### ISSUE TITLE
ODRC: overzicht alle publicaties

### ISSUE THREAD

**Issue by RutgerICATT** [GeneriekPublicatiePlatformWoo/registratie-component#5]
Uit PSA: Een beheerder wil in de beheer-interface van het ODRC (“Model- en publicatiebeheer”) een overzicht 
van alle bestaande (concept-)publicaties.

**Acceptatie criteria**

- In de ODRC-beheerinterface kan ik naar de publicaties gaan.
- Ik kan een lijst van alle publicaties zien (zie #2 )
  - Getoond worden de `identifier`, `verkorteTitel `, `officieleTitel` en de datum waarop de registratie is aangemaakt.
  - De lijst is standaard geordend van nieuw naar oud. De beheerder kan dit vervolgens aanpassen.
  - Er wordt pagination toegepast.
- De documentatie is bijgewerkt (Read the Docs)

**Taken**

- [ ]

**Comment by sergei-maertens** [comment]
Likely already realized via #3
