### ISSUE TITLE
ODRC: publicatie raadplegen (beheer)

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/registratie-component#50]
Als beheerder wil ik een publicatie kunnen raadplegen, zodat ik hier (later) beheer-activiteiten op kan uitvoeren.

**Acceptatie criteria**
- Vanuit het overzicht (#5) kan ik een publicatie openen en raadplegen:
  - Ik zie alle gegevens behorende bij die publicaties.
  - Ik zie alle documenten die aan de publicatie hangen.
  - Ik kan die documenten downloaden.
  - Ik kan alle gegevens bij die documenten zien. (eventueel na doorklikken)
  - Ik kan de logging inzien behorende bij die publicatie en de daaraan hangende documenten.
  - Ik kan terug keren naar het overzicht.

**Taken**

- [ ]

**Comment by sergei-maertens** [comment]
I've tackled 

> Ik kan de logging inzien behorende bij die publicatie en de daaraan hangende documenten.

via #83 just now, so I'm moving this into the current sprint.

**Comment by sergei-maertens** [comment]
Needs testing

**Comment by MarcoKlerks** [comment]
Test-resultaten:

>   * Ik zie alle documenten die aan de publicatie hangen.
>   * Ik kan die documenten downloaden.
>   * Ik kan alle gegevens bij die documenten zien. (eventueel na doorklikken)

Vanuit het ODPC kan ik nog geen documenten aanbieden. Documenten toevoegen via de beheer-interface is niet goed mogelijk, omdat:
- Ik handmatig een UUDI moet invoeren
- Ik geen bestand (bijv. pdf) kan uploaden. Daar is geen knopje voor o.i.d.

Kan iemand via een "achterdeur" een publicatie met een document aanmaken, zodat ik duit kan testen? Ik zal user stories toevoegen om het toevoegen van een document via de beheer-interface te verbeteren.

>   * Ik kan de logging inzien behorende bij die publicatie en de daaraan hangende documenten.

Gemeld als testbevinding bij #16 : _"Als ik in de beheer-interface naar een publicatie ga en rechtsboven klik op de knop "geschiedenis", dan zie ik alleen de updates, maar niet de creates en reads. Bij de "(audit) log entries" zie ik deze wel."_

**Comment by sergei-maertens** [comment]
Documenten upload hangt nog op andere user story: #19 

We zijn nog aan het voorbereiden daarop, nu is er enkel metadata beschikbaar.

De "geschiedenis" in de admin is onafhankelijk van de audit logs. Er is enige overlap - dit is wat ons framework ons out of the box geeft. De gevraagde logging functionaliteit zit volledig in de eigen audit logs implementatie.

**Comment by sergei-maertens** [comment]
Can be re-tested!

**Comment by MarcoKlerks** [comment]
Re-test succesvol!
