### ISSUE TITLE
ODRC: Publicatie intrekken

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/registratie-component#64]
Als gebruiker wil ik een publicatie in kunnen trekken, zodat ik een foutieve publicatie kan herstellen.

**Toelichting**
In [ODPC #39](https://github.com/GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component/issues/39) bediscussieerd. Het heeft de voorkeur dat met één API-call een publicatie inclusief documenten ingetrokken kan worden.

Afhankelijk van #49 . Hierin wordt `publicatiestatus` toegevoegd aan de API

**Acceptatie criteria**

- Via de API is het mogelijk om de `publicatiestatus` van een publicatie te wijzigen naar "ingetrokken". (Zie #49)
- Als de `publicatiestatus' van een publicatie wijzigt van "gepubliceerd" of "concept" naar "ingetrokken", dan wordt bij de aanhangige documenten:
  - als de huidige status al "ingetrokken" is, de `publicatiestatus` niet gewijzigd,
  - als de huidige status "gepubliceerd" is, de `publicatiestatus` gewijzigd naar "ingetrokken"
  - als de huidige status "concept" is, de `publicatiestatus` niet gewijzigd,
- De API specificatie is bijgewerkt (ReDoc, Swagger)
- De documentatie is bijgewerkt (Read the Docs)

De consequenties van het wijzigen van de 'publicatiestatus' naar "gepubliceerd" of "concept" vallen niet onder deze story.

**Taken**

make it so when a publication is revoked that the attached documents who are published also get revoked:
- [x] admin
- [x] api 

nice to have:
- [ ] create a unique audit trail event for revoking/publishing documents/publications

**Comment by sergei-maertens** [comment]
Reminder voor als dingen toch veranderen

Opmerking via Armijn - publicatiestatus van document is ook afhankelijk van publicatiestatus gerelateerde `publicatie` resource - bij het ontsluiten van Documenten direct via de list endpoint goed opletten met de queryset dat we niet per ongeluk documenten ontsluiten (dit speelt enkel als enkel de publicatie gemuteerd wordt en niet de gerelateerde documenten)

**Comment by sergei-maertens** [comment]
Staat op testomgeving

**Comment by MarcoKlerks** [comment]
Documentatie (Readthedocs) pak ik zelf even op ihkv #102 .
