### ISSUE TITLE
ODRC: Koppelen organisaties aan publicaties

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/registratie-component#66]
Als gemeente wil ik organisaties aan publicaties kunnen koppelen, zodat we kunnen voldoen aan de Diwoo-standaard

Let op! #26 is randvoorwaardelijk.

**Acceptatie criteria**

- Aan een publicatie kunnen de volgende attributen worden toegekend:
  - [`publisher`](https://standaarden.overheid.nl/diwoo/metadata/doc/0.9.4/diwoo-metadata_xsd_Complex_Type_diwoo_DiWooType#DiWooType_publisher) 
    - Verplicht; moet exact één organisatie als waarde hebben.
  - [`verantwoordelijke`](https://standaarden.overheid.nl/diwoo/metadata/doc/0.9.4/diwoo-metadata_xsd_Complex_Type_diwoo_DiWooType#DiWooType_verantwoordelijke)
    - Optioneel; mag max één organisatie als waarde hebben.
  - [`opsteller`
](https://standaarden.overheid.nl/diwoo/metadata/doc/0.9.4/diwoo-metadata_xsd_Complex_Type_diwoo_DiWooType#DiWooType_opsteller)
    - Optioneel; mag max één organisatie als waarde hebben.
- De API specificatie is bijgewerkt (ReDoc, Swagger)
- De documentatie is bijgewerkt (Read the Docs)

Laat ['medeverantwoordelijken'](https://standaarden.overheid.nl/diwoo/metadata/doc/0.9.4/diwoo-metadata_xsd_Complex_Type_diwoo_DiWooType#DiWooType_medeverantwoordelijken) nog maar even zitten. Ik kan niet verzinnen wanneer dat in de praktijk daadwerkelijk voorkomt.

**Taken**

- [x] Add foreignkey fields to the organisation model for the publication model:
    - publisher (required)
    - verantwoordelijke (optional)
    - opsteller (optional)
- [x] Add fields to admin
- [x] Add fields in the publication api
- [x] Make sure that only active organisations can be selected in the admin and api
- [x] update documentation

**Comment by sergei-maertens** [comment]
API design decision to make: use URI or just UUID of the organisation (I'm leaning towards the latter for simplicity).

**Comment by MarcoKlerks** [comment]
Voor de [sitemap](https://standaarden.overheid.nl/diwoo/metadata/diwoo-metadata-xsd)-generatie hebben we straks de URI's nodig. Als je de URI's dus gebruikt i.p.v. UUID's, dan hoeft het ODBP dus minder API-calls te maken bij het genereren van de sitemaps. Gebruik je UUID's om de link te leggen tussen publicaties en organisaties, dan moet het ODBP na het opvragen (GET) van de publicaties alsnog de organisaties  ovragen (GET) om aan de juiste  URI's te komen.

Ook wanneer KOOP ooit API's gaat ondersteunen, dan gaat het handig zijn dat op een publicatie de links met organisaties is gelegd via URI's i.p.v. UUID's.

Ik vermoed dus dat gebruik van URI's op de langere termijn de betere keuze is. Ik kan echter niet inschatten hoe veel complexer dat is dan gebruik van UUID's.

**Comment by sergei-maertens** [comment]
> dan hoeft het ODBP dus minder API-calls te maken bij het genereren van de sitemaps.

dit is sowieso niet aan de orde omdat we een bruikbaarder formaat willen weergeven bij de lees-acties, mijn opmerking gaat om de schrijf-acties en dan met name om het voor onszelf + ODBP het eenvoudigst te maken om te koppelen. En daarvoor neig ik naar de UUID (die sowieso onderdeel is van de URI).

Er is wel echt een technisch onderscheid tussen de eigen API en de identifiers/URL's gebruikt door KOOP/TOOI. Die specifieke URI is langs onze zijde gewoon "extra informatie" waar we de eigen resources niet aan ophangen, want als er extern iets verandert in een volgende versie, dan hebben wij een hoop extra werk wat we nu vermijden.

**Comment by MarcoKlerks** [comment]
oke

**Comment by MarcoKlerks** [comment]
@bart-maykin Nice-to-have: in de admin-interface kunnen bij `publisher` en `verantwoordelijke` alleen **actieve** organisaties ingevuld worden. Bij `opsteller` kunnen alle organisaties ingevuld worden.

**Comment by sergei-maertens** [comment]
reopening for acceptance testing

**Comment by felixcicatt** [comment]
> @bart-maykin Nice-to-have: in de admin-interface kunnen bij `publisher` en `verantwoordelijke` alleen **actieve** organisaties ingevuld worden. Bij `opsteller` kunnen alle organisaties ingevuld worden.

@MarcoKlerks Dubbel check: met deze nice to have hoeven we nog niets in het ODPC, toch? Daar kan je een enkele **actieve** organisatie kiezen die wordt doorgegeven als `publisher` en `verantwoordelijke`. Voor `opsteller` wordt nog niets doorgegeven.

**Comment by MarcoKlerks** [comment]
> > [@bart-maykin](https://github.com/bart-maykin) Nice-to-have: in de admin-interface kunnen bij `publisher` en `verantwoordelijke` alleen **actieve** organisaties ingevuld worden. Bij `opsteller` kunnen alle organisaties ingevuld worden.
> 
> [@MarcoKlerks](https://github.com/MarcoKlerks) Dubbel check: met deze nice to have hoeven we nog niets in het ODPC, toch? Daar kan je een enkele **actieve** organisatie kiezen die wordt doorgegeven als `publisher` en `verantwoordelijke`. Voor `opsteller` wordt nog niets doorgegeven.

@felixcicatt Correct, `opsteller` gaan we vanuit het ODPC voorlopig nog niet invullen.

**Comment by MarcoKlerks** [comment]
Testbevindingen:

Kleine verbeteringen mogelijk?:

1. Kan het veld `Drafter` net zo breed gemaakt worden als `Publisher` en `Liable orgnaisation`?
2. Kunnen de rode kruisjes achter `Liable organisation` en `Drafter` weggehaald worden? Ik had bijna per ongeluk een organisatie verwijderd. Ik dahct dat ik met dat kruisje het veld zou leegmaken.

Ik neem aan dat de veldnamen later vertaald worden naar het Nederlands, net zoals de vorige keer. :-)

**Comment by sergei-maertens** [comment]
@MarcoKlerks 

1. We gaan hier ook auto complete of raw ID fields van maken (maar zorgen dat dus de naam van de geselecteerde organisatie in beeld staat), dit lost vanzelf dit probleem op!
2. Deze zijn gekoppeld met de gebruikersrechten in de admin - als je groepen inricht en de rechten voor het verwijderen niet toekent, dan zullen deze kruisjes er niet staan. Jij ziet natuurlijk alles als superuser (with great power comes great responsibility :wink: ). Ik zou straks héél erg zorgvuldig omgaan met de OIDC/admin groepen en rechten.

> Ik neem aan dat de veldnamen later vertaald worden naar het Nederlands, net zoals de vorige keer. :-)

Inderdaad! Zal eind deze week/begin volgende week gebeuren.

**Comment by sergei-maertens** [comment]
Staat op testomgeving!
