### ISSUE TITLE
ODRC: documenthandelingen op documenten

### ISSUE THREAD

**Issue by MarcoKlerks** [GeneriekPublicatiePlatformWoo/registratie-component#76]
Als medewerker wil ik bij ieder document documenthandelingen kunnen vastleggen, zodat de burger dit kan raadplegen.

**Toelichting**
Helaas is dit verplicht vanuit DiWoo: [link](https://[standaarden.overheid.nl](https://standaarden.overheid.nl/diwoo/metadata/doc/0.9.4/diwoo-metadata_xsd_Complex_Type_diwoo_DiWooType#DiWooType_documenthandelingen)/diwoo/metadata/doc/0.9.4/diwoo-metadata_xsd_Complex_Type_diwoo_DiWooType#DiWooType_documenthandelingen).

N.a.v. discussie bij [ODPC #26](https://github.com/GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component/issues/26) ondersteunen we vooralsnog maar één documenthandeling per document, ook al kan volgens DiWoo een document ook meer dan één documenthandelingen kennen.

**Acceptatie criteria**

- Een 'document' (dus niet een 'publicatie') moet exact één documenthandeling bevatten.
- Een documenthandeling moet aan exact één 'document' gekoppeld zijn.
- Een documenthandeling omvat conform DiWoo:
  - een `soortHandeling` (verplicht, [enumeratie](https://[standaarden.overheid.nl](https://standaarden.overheid.nl/tooi/waardelijsten/work?work_uri=https%3A%2F%2Fidentifier.overheid.nl%2Ftooi%2Fset%2Fccw_plooi_documenthandelingen)/tooi/waardelijsten/work?work_uri=https%3A%2F%2Fidentifier.overheid.nl%2Ftooi%2Fset%2Fccw_plooi_documenthandelingen))
  - een `atTime` (verplicht, dateTime)
  - een `wasAssciatedWith` (optioneel, referentie naar 'organisatie' #26)
- Inzake de API:
  - Bij de creatie van een document moet een documenthandeling meegeleverd worden.
  - Bij de raadpleging van een document wordt ook de documenthandeling meegegeven in het antwoord.
  - Bij de mutatie van een document kan de documenthandeling gewijzigd worden.
  - Bij de verwijdering van een document wordt ook de de documenthandeling verwijderd.
- De documentatie en API-specificaties zijn bijgewerkt.

**Taken**

- [x] Add enum for documenthandelingen
- [x] (API) Ensure that on create of a document a documenthandeling can be proved, if not provided -> set a default (see https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/76#issuecomment-2419576422)
- [x] Return `documenthandelingen` array in the (detail and list) responses
- [x] Expose documenthandelingen in the admin interface - no need to show them in the changelist display

**Comment by sergei-maertens** [comment]
Discussed: set up a default for "vaststelling", so that the ODPC can drop the edit interface if needed.

See https://standaarden.overheid.nl/tooi/waardelijsten/expression?lijst_uri=https%3A%2F%2Fidentifier.overheid.nl%2Ftooi%2Fset%2Fccw_plooi_documenthandelingen%2F2

**Comment by sergei-maertens** [comment]
Documenthandelingen staat nu live op de testomgeving & zit in de latest docker image

**Comment by MarcoKlerks** [comment]
@felixcicatt Wat mij betreft kan deze op Done. Wat vind jij?
